// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package ad

import (
	"advertex/api/ad"
)

type ControllerV1 struct{}

func NewV1() ad.IAdV1 {
	return &ControllerV1{}
}
