version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: manifest/docker/develop.Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    command: ["gf", "run", "main.go"]
